extend = [
    { path = "scripts/makefile/cmd.toml" },
    { path = "scripts/makefile/db.toml" },
    { path = "scripts/makefile/openapi.toml" }
]

[env]
CARGO_PROFILE = "dev"
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
