/*
 * Trading API
 *
 * This API allow to interact with the trading system.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	hktrading_server "github.com/hungknow/hktrading_server/go"
)

func main() {
	log.Printf("Server started on port 9001")

	DefaultAPIService := hktrading_server.NewAPIService()
	DefaultAPIController := hktrading_server.NewDefaultAPIController(DefaultAPIService)

	router := hktrading_server.NewRouter(DefaultAPIController)

	log.Fatal(http.ListenAndServe(":9001", router))
}
