version: '3'
services:
  db:
    image: hungbn0112/timescaledb:pg16
    container_name: trading-db
    ports:
      - "9432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=trading
      - POSTGRES_USER=trading_user
      - POSTGRES_PASSWORD=aZAmkRBOjhdP5bw

volumes:
  db: