/*
 * Trading API
 *
 * This API allow to interact with the trading system. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package hktrading_server




type Candles struct {

	Times []int64 `json:"times,omitempty"`

	Closes []float64 `json:"closes,omitempty"`

	Highs []float64 `json:"highs,omitempty"`

	Lows []float64 `json:"lows,omitempty"`

	Vols []float64 `json:"vols,omitempty"`

	Opens []float64 `json:"opens,omitempty"`
}

// AssertCandlesRequired checks if the required fields are not zero-ed
func AssertCandlesRequired(obj Candles) error {
	return nil
}

// AssertCandlesConstraints checks if the values respects the defined constraints
func AssertCandlesConstraints(obj Candles) error {
	return nil
}
