/*
 * Trading API
 *
 * This API allow to interact with the trading system. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package hktrading_server




type HkError struct {

	Code int32 `json:"code,omitempty"`

	Message string `json:"message,omitempty"`
}

// AssertHkErrorRequired checks if the required fields are not zero-ed
func AssertHkErrorRequired(obj HkError) error {
	return nil
}

// AssertHkErrorConstraints checks if the values respects the defined constraints
func AssertHkErrorConstraints(obj HkError) error {
	return nil
}
