[tasks.sqitch-install]
depends = ["sqitch-install.mac"]

[tasks.sqitch-install.mac]
condition = { platforms = ["mac"] }
script = '''
    brew tap sqitchers/sqitch
    brew install sqitch --with-postgres-support
'''
